// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ColdStorage$Type } from "./ColdStorage";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ColdStorage"]: ColdStorage$Type;
    ["@bgrusnak/solidity-icoset/contracts/management/ColdStorage.sol:ColdStorage"]: ColdStorage$Type;
  }
}
