// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { AggregatorInterface$Type } from "./AggregatorInterface";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AggregatorInterface"]: AggregatorInterface$Type;
    ["@chainlink/contracts/src/v0.8/interfaces/AggregatorInterface.sol:AggregatorInterface"]: AggregatorInterface$Type;
  }
}
