/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as management from "./management";
export type { management };
import type * as utils from "./utils";
export type { utils };
