// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IFreezable$Type } from "./IFreezable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IFreezable"]: IFreezable$Type;
    ["contracts/tokens/IFreezable.sol:IFreezable"]: IFreezable$Type;
  }
}
