// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IVesting$Type } from "./IVesting";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IVesting"]: IVesting$Type;
    ["@bgrusnak/solidity-icoset/contracts/management/IVesting.sol:IVesting"]: IVesting$Type;
  }
}
