// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { CXBTokenVesting$Type } from "./CXBTokenVesting";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CXBTokenVesting"]: CXBTokenVesting$Type;
    ["contracts/utils/CXBTokenVesting.sol:CXBTokenVesting"]: CXBTokenVesting$Type;
  }
}
