// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { AuthorityUtils$Type } from "./AuthorityUtils";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AuthorityUtils"]: AuthorityUtils$Type;
    ["@openzeppelin/contracts/access/manager/AuthorityUtils.sol:AuthorityUtils"]: AuthorityUtils$Type;
  }
}
