// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { AbiParameterToPrimitiveType, GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface MockChainlink$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "MockChainlink",
  "sourceName": "contracts/mocks/MockChainlink.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "int256",
          "name": "_value",
          "type": "int256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "constructor"
    },
    {
      "inputs": [],
      "name": "decimals",
      "outputs": [
        {
          "internalType": "uint8",
          "name": "",
          "type": "uint8"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "latestAnswer",
      "outputs": [
        {
          "internalType": "int256",
          "name": "",
          "type": "int256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x608060405234801561001057600080fd5b506040516100c63803806100c683398101604081905261002f91610037565b600055610050565b60006020828403121561004957600080fd5b5051919050565b60688061005e6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c8063313ce56714603757806350d25bcd14604b575b600080fd5b604051600681526020015b60405180910390f35b600054604051908152602001604256fea164736f6c6343000814000a",
  "deployedBytecode": "0x6080604052348015600f57600080fd5b506004361060325760003560e01c8063313ce56714603757806350d25bcd14604b575b600080fd5b604051600681526020015b60405180910390f35b600054604051908152602001604256fea164736f6c6343000814000a",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "contracts/mocks/MockChainlink.sol:MockChainlink",
    constructorArgs: [_value: AbiParameterToPrimitiveType<{"name":"_value","type":"int256"}>],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<MockChainlink$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "contracts/mocks/MockChainlink.sol:MockChainlink",
    constructorArgs: [_value: AbiParameterToPrimitiveType<{"name":"_value","type":"int256"}>],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<MockChainlink$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "contracts/mocks/MockChainlink.sol:MockChainlink",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<MockChainlink$Type["abi"]>>;
}
