/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PresaleManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "PUBLIC_ROLE"
      | "SALT"
      | "at"
      | "balanceOf"
      | "bonus"
      | "buy"
      | "canCall"
      | "cancel"
      | "cashPercent"
      | "consumeScheduledOp"
      | "destroy"
      | "execute"
      | "expiration"
      | "freeze"
      | "getAccess"
      | "getNonce"
      | "getResultAmount"
      | "getRoleAdmin"
      | "getRoleGrantDelay"
      | "getRoleGuardian"
      | "getSchedule"
      | "getTargetAdminDelay"
      | "getTargetFunctionRole"
      | "grantRole"
      | "hasRate"
      | "hasRole"
      | "hashOperation"
      | "isTargetClosed"
      | "labelRole"
      | "length"
      | "minSetback"
      | "multicall"
      | "owner"
      | "pause"
      | "paused"
      | "rate"
      | "redeem"
      | "renounceOwnership"
      | "renounceRole"
      | "revokeRole"
      | "schedule"
      | "setBonus"
      | "setCashPercent"
      | "setGrantDelay"
      | "setRate"
      | "setRoleAdmin"
      | "setRoleGuardian"
      | "setTargetAdminDelay"
      | "setTargetClosed"
      | "setTargetFunctionRole"
      | "setToken"
      | "setTokenPercent"
      | "setVesting"
      | "token"
      | "tokenPercent"
      | "transferAuthority"
      | "transferOwnership"
      | "unfreeze"
      | "unpause"
      | "updateAuthority"
      | "vesting"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BoughtTokens"
      | "OperationCanceled"
      | "OperationExecuted"
      | "OperationScheduled"
      | "OwnershipTransferred"
      | "Paused"
      | "ReferralsProvided"
      | "RoleAdminChanged"
      | "RoleGrantDelayChanged"
      | "RoleGranted"
      | "RoleGuardianChanged"
      | "RoleLabel"
      | "RoleRevoked"
      | "TargetAdminDelayUpdated"
      | "TargetClosed"
      | "TargetFunctionRoleUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PUBLIC_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "SALT", values?: undefined): string;
  encodeFunctionData(functionFragment: "at", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "bonus", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canCall",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancel",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cashPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "consumeScheduledOp",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "destroy",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "expiration",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "freeze", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "getAccess",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getNonce", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getResultAmount",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleGrantDelay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleGuardian",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSchedule",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTargetAdminDelay",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTargetFunctionRole",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hashOperation",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTargetClosed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "labelRole",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "length", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "minSetback",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "multicall",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "rate", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "schedule",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBonus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCashPercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGrantDelay",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRate",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRoleAdmin",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRoleGuardian",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTargetAdminDelay",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTargetClosed",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTargetFunctionRole",
    values: [AddressLike, BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenPercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVesting",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferAuthority",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unfreeze",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateAuthority",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "vesting", values?: undefined): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PUBLIC_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "SALT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "at", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bonus", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canCall", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cashPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "consumeScheduledOp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "destroy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "expiration", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "freeze", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAccess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getResultAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleGrantDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTargetAdminDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTargetFunctionRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hashOperation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTargetClosed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "labelRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "length", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minSetback", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "multicall", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "schedule", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBonus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCashPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGrantDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRoleGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTargetAdminDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTargetClosed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTargetFunctionRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTokenPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setVesting", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unfreeze", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vesting", data: BytesLike): Result;
}

export namespace BoughtTokensEvent {
  export type InputTuple = [
    sender: AddressLike,
    currency: AddressLike,
    value: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    currency: string,
    value: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    sender: string;
    currency: string;
    value: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperationCanceledEvent {
  export type InputTuple = [operationId: BytesLike, nonce: BigNumberish];
  export type OutputTuple = [operationId: string, nonce: bigint];
  export interface OutputObject {
    operationId: string;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperationExecutedEvent {
  export type InputTuple = [operationId: BytesLike, nonce: BigNumberish];
  export type OutputTuple = [operationId: string, nonce: bigint];
  export interface OutputObject {
    operationId: string;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperationScheduledEvent {
  export type InputTuple = [
    operationId: BytesLike,
    nonce: BigNumberish,
    schedule: BigNumberish,
    caller: AddressLike,
    target: AddressLike,
    data: BytesLike
  ];
  export type OutputTuple = [
    operationId: string,
    nonce: bigint,
    schedule: bigint,
    caller: string,
    target: string,
    data: string
  ];
  export interface OutputObject {
    operationId: string;
    nonce: bigint;
    schedule: bigint;
    caller: string;
    target: string;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralsProvidedEvent {
  export type InputTuple = [
    sender: AddressLike,
    referral: AddressLike,
    currency: AddressLike,
    amount: BigNumberish,
    cashAmount: BigNumberish,
    tokenAmount: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    referral: string,
    currency: string,
    amount: bigint,
    cashAmount: bigint,
    tokenAmount: bigint
  ];
  export interface OutputObject {
    sender: string;
    referral: string;
    currency: string;
    amount: bigint;
    cashAmount: bigint;
    tokenAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [roleId: BigNumberish, admin: BigNumberish];
  export type OutputTuple = [roleId: bigint, admin: bigint];
  export interface OutputObject {
    roleId: bigint;
    admin: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantDelayChangedEvent {
  export type InputTuple = [
    roleId: BigNumberish,
    delay: BigNumberish,
    since: BigNumberish
  ];
  export type OutputTuple = [roleId: bigint, delay: bigint, since: bigint];
  export interface OutputObject {
    roleId: bigint;
    delay: bigint;
    since: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    roleId: BigNumberish,
    account: AddressLike,
    delay: BigNumberish,
    since: BigNumberish,
    newMember: boolean
  ];
  export type OutputTuple = [
    roleId: bigint,
    account: string,
    delay: bigint,
    since: bigint,
    newMember: boolean
  ];
  export interface OutputObject {
    roleId: bigint;
    account: string;
    delay: bigint;
    since: bigint;
    newMember: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGuardianChangedEvent {
  export type InputTuple = [roleId: BigNumberish, guardian: BigNumberish];
  export type OutputTuple = [roleId: bigint, guardian: bigint];
  export interface OutputObject {
    roleId: bigint;
    guardian: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleLabelEvent {
  export type InputTuple = [roleId: BigNumberish, label: string];
  export type OutputTuple = [roleId: bigint, label: string];
  export interface OutputObject {
    roleId: bigint;
    label: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [roleId: BigNumberish, account: AddressLike];
  export type OutputTuple = [roleId: bigint, account: string];
  export interface OutputObject {
    roleId: bigint;
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TargetAdminDelayUpdatedEvent {
  export type InputTuple = [
    target: AddressLike,
    delay: BigNumberish,
    since: BigNumberish
  ];
  export type OutputTuple = [target: string, delay: bigint, since: bigint];
  export interface OutputObject {
    target: string;
    delay: bigint;
    since: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TargetClosedEvent {
  export type InputTuple = [target: AddressLike, closed: boolean];
  export type OutputTuple = [target: string, closed: boolean];
  export interface OutputObject {
    target: string;
    closed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TargetFunctionRoleUpdatedEvent {
  export type InputTuple = [
    target: AddressLike,
    selector: BytesLike,
    roleId: BigNumberish
  ];
  export type OutputTuple = [target: string, selector: string, roleId: bigint];
  export interface OutputObject {
    target: string;
    selector: string;
    roleId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PresaleManager extends BaseContract {
  connect(runner?: ContractRunner | null): PresaleManager;
  waitForDeployment(): Promise<this>;

  interface: PresaleManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [bigint], "view">;

  PUBLIC_ROLE: TypedContractMethod<[], [bigint], "view">;

  SALT: TypedContractMethod<[], [bigint], "view">;

  at: TypedContractMethod<[ratePos: BigNumberish], [[string, bigint]], "view">;

  balanceOf: TypedContractMethod<[currency: AddressLike], [bigint], "view">;

  bonus: TypedContractMethod<[], [bigint], "view">;

  buy: TypedContractMethod<
    [currency: AddressLike, value: BigNumberish, referral: AddressLike],
    [boolean],
    "nonpayable"
  >;

  canCall: TypedContractMethod<
    [caller: AddressLike, target: AddressLike, selector: BytesLike],
    [[boolean, bigint] & { immediate: boolean; delay: bigint }],
    "view"
  >;

  cancel: TypedContractMethod<
    [caller: AddressLike, target: AddressLike, data: BytesLike],
    [bigint],
    "nonpayable"
  >;

  cashPercent: TypedContractMethod<[], [bigint], "view">;

  consumeScheduledOp: TypedContractMethod<
    [caller: AddressLike, data: BytesLike],
    [void],
    "nonpayable"
  >;

  destroy: TypedContractMethod<
    [_to: AddressLike, newAuthority: AddressLike],
    [void],
    "nonpayable"
  >;

  execute: TypedContractMethod<
    [target: AddressLike, data: BytesLike],
    [bigint],
    "payable"
  >;

  expiration: TypedContractMethod<[], [bigint], "view">;

  freeze: TypedContractMethod<[target: AddressLike], [void], "nonpayable">;

  getAccess: TypedContractMethod<
    [roleId: BigNumberish, account: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        since: bigint;
        currentDelay: bigint;
        pendingDelay: bigint;
        effect: bigint;
      }
    ],
    "view"
  >;

  getNonce: TypedContractMethod<[id: BytesLike], [bigint], "view">;

  getResultAmount: TypedContractMethod<
    [currency: AddressLike, value: BigNumberish],
    [bigint],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[roleId: BigNumberish], [bigint], "view">;

  getRoleGrantDelay: TypedContractMethod<
    [roleId: BigNumberish],
    [bigint],
    "view"
  >;

  getRoleGuardian: TypedContractMethod<
    [roleId: BigNumberish],
    [bigint],
    "view"
  >;

  getSchedule: TypedContractMethod<[id: BytesLike], [bigint], "view">;

  getTargetAdminDelay: TypedContractMethod<
    [target: AddressLike],
    [bigint],
    "view"
  >;

  getTargetFunctionRole: TypedContractMethod<
    [target: AddressLike, selector: BytesLike],
    [bigint],
    "view"
  >;

  grantRole: TypedContractMethod<
    [roleId: BigNumberish, account: AddressLike, executionDelay: BigNumberish],
    [void],
    "nonpayable"
  >;

  hasRate: TypedContractMethod<[currency: AddressLike], [boolean], "view">;

  hasRole: TypedContractMethod<
    [roleId: BigNumberish, account: AddressLike],
    [[boolean, bigint] & { isMember: boolean; executionDelay: bigint }],
    "view"
  >;

  hashOperation: TypedContractMethod<
    [caller: AddressLike, target: AddressLike, data: BytesLike],
    [string],
    "view"
  >;

  isTargetClosed: TypedContractMethod<[target: AddressLike], [boolean], "view">;

  labelRole: TypedContractMethod<
    [roleId: BigNumberish, label: string],
    [void],
    "nonpayable"
  >;

  length: TypedContractMethod<[], [bigint], "view">;

  minSetback: TypedContractMethod<[], [bigint], "view">;

  multicall: TypedContractMethod<[data: BytesLike[]], [string[]], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  rate: TypedContractMethod<[currency: AddressLike], [bigint], "view">;

  redeem: TypedContractMethod<
    [currency: AddressLike, _to: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  renounceRole: TypedContractMethod<
    [roleId: BigNumberish, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [roleId: BigNumberish, account: AddressLike],
    [void],
    "nonpayable"
  >;

  schedule: TypedContractMethod<
    [target: AddressLike, data: BytesLike, when: BigNumberish],
    [[string, bigint] & { operationId: string; nonce: bigint }],
    "nonpayable"
  >;

  setBonus: TypedContractMethod<[bonus: BigNumberish], [void], "nonpayable">;

  setCashPercent: TypedContractMethod<
    [percent: BigNumberish],
    [void],
    "nonpayable"
  >;

  setGrantDelay: TypedContractMethod<
    [roleId: BigNumberish, newDelay: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRate: TypedContractMethod<
    [currency: AddressLike, rate: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  setRoleAdmin: TypedContractMethod<
    [roleId: BigNumberish, admin: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRoleGuardian: TypedContractMethod<
    [roleId: BigNumberish, guardian: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTargetAdminDelay: TypedContractMethod<
    [target: AddressLike, newDelay: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTargetClosed: TypedContractMethod<
    [target: AddressLike, closed: boolean],
    [void],
    "nonpayable"
  >;

  setTargetFunctionRole: TypedContractMethod<
    [target: AddressLike, selectors: BytesLike[], roleId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setToken: TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;

  setTokenPercent: TypedContractMethod<
    [percent: BigNumberish],
    [void],
    "nonpayable"
  >;

  setVesting: TypedContractMethod<
    [_vesting: AddressLike],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  tokenPercent: TypedContractMethod<[], [bigint], "view">;

  transferAuthority: TypedContractMethod<
    [newAuthority: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unfreeze: TypedContractMethod<[target: AddressLike], [void], "nonpayable">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateAuthority: TypedContractMethod<
    [target: AddressLike, newAuthority: AddressLike],
    [void],
    "nonpayable"
  >;

  vesting: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PUBLIC_ROLE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SALT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "at"
  ): TypedContractMethod<[ratePos: BigNumberish], [[string, bigint]], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[currency: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "bonus"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<
    [currency: AddressLike, value: BigNumberish, referral: AddressLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "canCall"
  ): TypedContractMethod<
    [caller: AddressLike, target: AddressLike, selector: BytesLike],
    [[boolean, bigint] & { immediate: boolean; delay: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<
    [caller: AddressLike, target: AddressLike, data: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cashPercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "consumeScheduledOp"
  ): TypedContractMethod<
    [caller: AddressLike, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "destroy"
  ): TypedContractMethod<
    [_to: AddressLike, newAuthority: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [target: AddressLike, data: BytesLike],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "expiration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "freeze"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAccess"
  ): TypedContractMethod<
    [roleId: BigNumberish, account: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        since: bigint;
        currentDelay: bigint;
        pendingDelay: bigint;
        effect: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNonce"
  ): TypedContractMethod<[id: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getResultAmount"
  ): TypedContractMethod<
    [currency: AddressLike, value: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[roleId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleGrantDelay"
  ): TypedContractMethod<[roleId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleGuardian"
  ): TypedContractMethod<[roleId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSchedule"
  ): TypedContractMethod<[id: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTargetAdminDelay"
  ): TypedContractMethod<[target: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTargetFunctionRole"
  ): TypedContractMethod<
    [target: AddressLike, selector: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [roleId: BigNumberish, account: AddressLike, executionDelay: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRate"
  ): TypedContractMethod<[currency: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [roleId: BigNumberish, account: AddressLike],
    [[boolean, bigint] & { isMember: boolean; executionDelay: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashOperation"
  ): TypedContractMethod<
    [caller: AddressLike, target: AddressLike, data: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTargetClosed"
  ): TypedContractMethod<[target: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "labelRole"
  ): TypedContractMethod<
    [roleId: BigNumberish, label: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "length"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minSetback"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "multicall"
  ): TypedContractMethod<[data: BytesLike[]], [string[]], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "rate"
  ): TypedContractMethod<[currency: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "redeem"
  ): TypedContractMethod<
    [currency: AddressLike, _to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [roleId: BigNumberish, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [roleId: BigNumberish, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "schedule"
  ): TypedContractMethod<
    [target: AddressLike, data: BytesLike, when: BigNumberish],
    [[string, bigint] & { operationId: string; nonce: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBonus"
  ): TypedContractMethod<[bonus: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCashPercent"
  ): TypedContractMethod<[percent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGrantDelay"
  ): TypedContractMethod<
    [roleId: BigNumberish, newDelay: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRate"
  ): TypedContractMethod<
    [currency: AddressLike, rate: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRoleAdmin"
  ): TypedContractMethod<
    [roleId: BigNumberish, admin: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRoleGuardian"
  ): TypedContractMethod<
    [roleId: BigNumberish, guardian: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTargetAdminDelay"
  ): TypedContractMethod<
    [target: AddressLike, newDelay: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTargetClosed"
  ): TypedContractMethod<
    [target: AddressLike, closed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTargetFunctionRole"
  ): TypedContractMethod<
    [target: AddressLike, selectors: BytesLike[], roleId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setToken"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTokenPercent"
  ): TypedContractMethod<[percent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVesting"
  ): TypedContractMethod<[_vesting: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenPercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferAuthority"
  ): TypedContractMethod<[newAuthority: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unfreeze"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAuthority"
  ): TypedContractMethod<
    [target: AddressLike, newAuthority: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vesting"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BoughtTokens"
  ): TypedContractEvent<
    BoughtTokensEvent.InputTuple,
    BoughtTokensEvent.OutputTuple,
    BoughtTokensEvent.OutputObject
  >;
  getEvent(
    key: "OperationCanceled"
  ): TypedContractEvent<
    OperationCanceledEvent.InputTuple,
    OperationCanceledEvent.OutputTuple,
    OperationCanceledEvent.OutputObject
  >;
  getEvent(
    key: "OperationExecuted"
  ): TypedContractEvent<
    OperationExecutedEvent.InputTuple,
    OperationExecutedEvent.OutputTuple,
    OperationExecutedEvent.OutputObject
  >;
  getEvent(
    key: "OperationScheduled"
  ): TypedContractEvent<
    OperationScheduledEvent.InputTuple,
    OperationScheduledEvent.OutputTuple,
    OperationScheduledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralsProvided"
  ): TypedContractEvent<
    ReferralsProvidedEvent.InputTuple,
    ReferralsProvidedEvent.OutputTuple,
    ReferralsProvidedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGrantDelayChanged"
  ): TypedContractEvent<
    RoleGrantDelayChangedEvent.InputTuple,
    RoleGrantDelayChangedEvent.OutputTuple,
    RoleGrantDelayChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGuardianChanged"
  ): TypedContractEvent<
    RoleGuardianChangedEvent.InputTuple,
    RoleGuardianChangedEvent.OutputTuple,
    RoleGuardianChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleLabel"
  ): TypedContractEvent<
    RoleLabelEvent.InputTuple,
    RoleLabelEvent.OutputTuple,
    RoleLabelEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TargetAdminDelayUpdated"
  ): TypedContractEvent<
    TargetAdminDelayUpdatedEvent.InputTuple,
    TargetAdminDelayUpdatedEvent.OutputTuple,
    TargetAdminDelayUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TargetClosed"
  ): TypedContractEvent<
    TargetClosedEvent.InputTuple,
    TargetClosedEvent.OutputTuple,
    TargetClosedEvent.OutputObject
  >;
  getEvent(
    key: "TargetFunctionRoleUpdated"
  ): TypedContractEvent<
    TargetFunctionRoleUpdatedEvent.InputTuple,
    TargetFunctionRoleUpdatedEvent.OutputTuple,
    TargetFunctionRoleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BoughtTokens(address,address,uint256,uint256)": TypedContractEvent<
      BoughtTokensEvent.InputTuple,
      BoughtTokensEvent.OutputTuple,
      BoughtTokensEvent.OutputObject
    >;
    BoughtTokens: TypedContractEvent<
      BoughtTokensEvent.InputTuple,
      BoughtTokensEvent.OutputTuple,
      BoughtTokensEvent.OutputObject
    >;

    "OperationCanceled(bytes32,uint32)": TypedContractEvent<
      OperationCanceledEvent.InputTuple,
      OperationCanceledEvent.OutputTuple,
      OperationCanceledEvent.OutputObject
    >;
    OperationCanceled: TypedContractEvent<
      OperationCanceledEvent.InputTuple,
      OperationCanceledEvent.OutputTuple,
      OperationCanceledEvent.OutputObject
    >;

    "OperationExecuted(bytes32,uint32)": TypedContractEvent<
      OperationExecutedEvent.InputTuple,
      OperationExecutedEvent.OutputTuple,
      OperationExecutedEvent.OutputObject
    >;
    OperationExecuted: TypedContractEvent<
      OperationExecutedEvent.InputTuple,
      OperationExecutedEvent.OutputTuple,
      OperationExecutedEvent.OutputObject
    >;

    "OperationScheduled(bytes32,uint32,uint48,address,address,bytes)": TypedContractEvent<
      OperationScheduledEvent.InputTuple,
      OperationScheduledEvent.OutputTuple,
      OperationScheduledEvent.OutputObject
    >;
    OperationScheduled: TypedContractEvent<
      OperationScheduledEvent.InputTuple,
      OperationScheduledEvent.OutputTuple,
      OperationScheduledEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ReferralsProvided(address,address,address,uint256,uint256,uint256)": TypedContractEvent<
      ReferralsProvidedEvent.InputTuple,
      ReferralsProvidedEvent.OutputTuple,
      ReferralsProvidedEvent.OutputObject
    >;
    ReferralsProvided: TypedContractEvent<
      ReferralsProvidedEvent.InputTuple,
      ReferralsProvidedEvent.OutputTuple,
      ReferralsProvidedEvent.OutputObject
    >;

    "RoleAdminChanged(uint64,uint64)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGrantDelayChanged(uint64,uint32,uint48)": TypedContractEvent<
      RoleGrantDelayChangedEvent.InputTuple,
      RoleGrantDelayChangedEvent.OutputTuple,
      RoleGrantDelayChangedEvent.OutputObject
    >;
    RoleGrantDelayChanged: TypedContractEvent<
      RoleGrantDelayChangedEvent.InputTuple,
      RoleGrantDelayChangedEvent.OutputTuple,
      RoleGrantDelayChangedEvent.OutputObject
    >;

    "RoleGranted(uint64,address,uint32,uint48,bool)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleGuardianChanged(uint64,uint64)": TypedContractEvent<
      RoleGuardianChangedEvent.InputTuple,
      RoleGuardianChangedEvent.OutputTuple,
      RoleGuardianChangedEvent.OutputObject
    >;
    RoleGuardianChanged: TypedContractEvent<
      RoleGuardianChangedEvent.InputTuple,
      RoleGuardianChangedEvent.OutputTuple,
      RoleGuardianChangedEvent.OutputObject
    >;

    "RoleLabel(uint64,string)": TypedContractEvent<
      RoleLabelEvent.InputTuple,
      RoleLabelEvent.OutputTuple,
      RoleLabelEvent.OutputObject
    >;
    RoleLabel: TypedContractEvent<
      RoleLabelEvent.InputTuple,
      RoleLabelEvent.OutputTuple,
      RoleLabelEvent.OutputObject
    >;

    "RoleRevoked(uint64,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TargetAdminDelayUpdated(address,uint32,uint48)": TypedContractEvent<
      TargetAdminDelayUpdatedEvent.InputTuple,
      TargetAdminDelayUpdatedEvent.OutputTuple,
      TargetAdminDelayUpdatedEvent.OutputObject
    >;
    TargetAdminDelayUpdated: TypedContractEvent<
      TargetAdminDelayUpdatedEvent.InputTuple,
      TargetAdminDelayUpdatedEvent.OutputTuple,
      TargetAdminDelayUpdatedEvent.OutputObject
    >;

    "TargetClosed(address,bool)": TypedContractEvent<
      TargetClosedEvent.InputTuple,
      TargetClosedEvent.OutputTuple,
      TargetClosedEvent.OutputObject
    >;
    TargetClosed: TypedContractEvent<
      TargetClosedEvent.InputTuple,
      TargetClosedEvent.OutputTuple,
      TargetClosedEvent.OutputObject
    >;

    "TargetFunctionRoleUpdated(address,bytes4,uint64)": TypedContractEvent<
      TargetFunctionRoleUpdatedEvent.InputTuple,
      TargetFunctionRoleUpdatedEvent.OutputTuple,
      TargetFunctionRoleUpdatedEvent.OutputObject
    >;
    TargetFunctionRoleUpdated: TypedContractEvent<
      TargetFunctionRoleUpdatedEvent.InputTuple,
      TargetFunctionRoleUpdatedEvent.OutputTuple,
      TargetFunctionRoleUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
