// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { CXBTColdStorage$Type } from "./CXBTColdStorage";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CXBTColdStorage"]: CXBTColdStorage$Type;
    ["contracts/management/CXBTColdStorage.sol:CXBTColdStorage"]: CXBTColdStorage$Type;
  }
}
