// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Vesting$Type } from "./Vesting";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Vesting"]: Vesting$Type;
    ["@bgrusnak/solidity-icoset/contracts/management/Vesting.sol:Vesting"]: Vesting$Type;
  }
}
