// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { AggregatorV2V3Interface$Type } from "./AggregatorV2V3Interface";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AggregatorV2V3Interface"]: AggregatorV2V3Interface$Type;
    ["@chainlink/contracts/src/v0.8/interfaces/AggregatorV2V3Interface.sol:AggregatorV2V3Interface"]: AggregatorV2V3Interface$Type;
  }
}
