// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { PresaleManager$Type } from "./PresaleManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PresaleManager"]: PresaleManager$Type;
    ["contracts/management/PresaleManager.sol:PresaleManager"]: PresaleManager$Type;
  }
}
