// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { CXBToken$Type } from "./CXBToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CXBToken"]: CXBToken$Type;
    ["contracts/tokens/CXBToken.sol:CXBToken"]: CXBToken$Type;
  }
}
