/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface IBountyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "balanceOf"
      | "clean"
      | "empty"
      | "give"
      | "isAgent"
      | "refuel"
      | "setVesting"
      | "vesting"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "clean", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "empty", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "give",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "refuel",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVesting",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "vesting", values?: undefined): string;

  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "clean", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "empty", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "give", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refuel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setVesting", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vesting", data: BytesLike): Result;
}

export interface IBounty extends BaseContract {
  connect(runner?: ContractRunner | null): IBounty;
  waitForDeployment(): Promise<this>;

  interface: IBountyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  balanceOf: TypedContractMethod<[target: AddressLike], [bigint], "view">;

  clean: TypedContractMethod<[_to: AddressLike], [void], "nonpayable">;

  empty: TypedContractMethod<[target: AddressLike], [void], "nonpayable">;

  give: TypedContractMethod<
    [target: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  isAgent: TypedContractMethod<[target: AddressLike], [boolean], "view">;

  refuel: TypedContractMethod<
    [agent: AddressLike, addAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setVesting: TypedContractMethod<
    [_vesting: AddressLike],
    [void],
    "nonpayable"
  >;

  vesting: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[target: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "clean"
  ): TypedContractMethod<[_to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "empty"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "give"
  ): TypedContractMethod<
    [target: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isAgent"
  ): TypedContractMethod<[target: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "refuel"
  ): TypedContractMethod<
    [agent: AddressLike, addAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVesting"
  ): TypedContractMethod<[_vesting: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vesting"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
