// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Freezable$Type } from "./Freezable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Freezable"]: Freezable$Type;
    ["@bgrusnak/solidity-icoset/contracts/utils/Freezable.sol:Freezable"]: Freezable$Type;
  }
}
