// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface EnumerableMap$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "EnumerableMap",
  "sourceName": "@openzeppelin/contracts/utils/structs/EnumerableMap.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "key",
          "type": "bytes32"
        }
      ],
      "name": "EnumerableMapNonexistentKey",
      "type": "error"
    }
  ],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212201e14c655f761d48e972aef2ede3e56bdcb5cc759943d2e736c99d695c0bbceaf64736f6c63430008140033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212201e14c655f761d48e972aef2ede3e56bdcb5cc759943d2e736c99d695c0bbceaf64736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "EnumerableMap",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EnumerableMap$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/structs/EnumerableMap.sol:EnumerableMap",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EnumerableMap$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "EnumerableMap",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EnumerableMap$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/structs/EnumerableMap.sol:EnumerableMap",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EnumerableMap$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "EnumerableMap",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EnumerableMap$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/structs/EnumerableMap.sol:EnumerableMap",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EnumerableMap$Type["abi"]>>;
}
