// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { CXBTokenBounty$Type } from "./CXBTokenBounty";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CXBTokenBounty"]: CXBTokenBounty$Type;
    ["contracts/management/CXBTokenBounty.sol:CXBTokenBounty"]: CXBTokenBounty$Type;
  }
}
