// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Purchase$Type } from "./Purchase";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Purchase"]: Purchase$Type;
    ["@bgrusnak/solidity-icoset/contracts/management/Purchase.sol:Purchase"]: Purchase$Type;
  }
}
