// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { CXBTokenAirdrop$Type } from "./CXBTokenAirdrop";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CXBTokenAirdrop"]: CXBTokenAirdrop$Type;
    ["contracts/utils/CXBTokenAirdrop.sol:CXBTokenAirdrop"]: CXBTokenAirdrop$Type;
  }
}
