// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { BitMaps$Type } from "./BitMaps";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BitMaps"]: BitMaps$Type;
    ["@openzeppelin/contracts/utils/structs/BitMaps.sol:BitMaps"]: BitMaps$Type;
  }
}
